menu:
    Blog: /
    Archive: /archives/
    gitHub: https://github.com/abalone0204
    twitter: https://twitter.com/TinyDenny
    Linkedin: https://www.linkedin.com/in/denny-ku-a9a21396?trk=hp-identity-name
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: abalone0204
duoshuo: 

# Analytics
# google-analytics:
ga: UA-76858432-1
# baidu-analytics:
ba: 

# Copyright Infomation
startyear: 2015

# Font CDN
#true : use google fonts api, not stable for chinese visitor sometimes, caused by force majeure factor
#false: use useso fonts api instead of google's, great response speed for chinese visitor
googlefonts: false
